config/routes.rb
Rails.application.routes.draw do
 
  root 'bots#index'
  
  resources :bots

  get 'new', to: 'bots#new'
  get 'show', to: 'bots#show'
  get 'edit', to: 'bots#edit'
  put 'delete', to: 'bots#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot.rb
class Bot < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController

    def index 
      @bot = Bot.all
    end

    def show
        @bot = Bot.find(params[:id])
    end 

    def new 
      @bot = Bot.new
    end 
     
    def update 
        @bot = Bot.find(params[:id])
        @bot.update_attributes(bot_params)
        @bot.save!
        if @bot.save
        redirect_to @bot
        end
    end 
    
    

    def destroy
        @bot = Bot.find(params[:id])
        @bot.destroy
        redirect_to root_path
    end 

  def edit
    @bot = Bot.find(params[:id])
  end
    private 

    def bot_params
        params.require(:bot).permit(:name, :problem)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/views/bots/edit.html.erb
<h1>Edit bot</h1>


<%= simple_form_for @bot do |f| %>
    <%= f.input :name %>
    <%= f.input :problem %>
    <%= f.button :submit %>
  <% end %>

  <%= link_to "Home", root_path %>
  <%= link_to "Bot", bot_path %>

app/views/bots/index.html.erb
<h1>All bots<h1>

<% @bot.each do |bot|%>
    
    <%=bot.name%>  <%=bot.problem%>
  
    <hr>
    

    <% end %>
  

app/views/bots/new.html.erb
<h1>New Bot</h1>

<%= simple_form_for @bot do |f| %>
    <%= f.input :name %>
    <%= f.input :problem %>
    <%= f.button :submit %>
  <% end %>

  <%= link_to "Home", root_path %>

app/views/bots/show.html.erb
<h1>Im A bot</h1>


<%=@bot.name%>:  <%=@bot.problem%>

<%= link_to "Home", root_path %>
<%= link_to "Edit", edit_bot_path %>
<%= link_to "Destroy", bot_path(@bot), method: :delete, data: { confirm: 'Are you sure?' }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Botiana</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>